# Type signatures for SecretsCache
class SecretsCache
  DEFAULT_VERSION_STAGE: String
  NAMESPACE: String

  def self.instance: () -> SecretsCache
  def self.get_many: (Array[String] | Array[lookupHash] secret_ids) -> cacheResult
  def self.set_many: (Array[Hash[Symbol, untyped]] secrets) -> void
  def self.clear: () -> void

  def get_many: (Array[String] | Array[lookupHash] secret_ids) -> cacheResult
  def set_many: (Array[Hash[Symbol, untyped]] secrets) -> void
  def clear: () -> void

  private

  def normalize_lookups: (Array[String] | Array[lookupHash] secret_ids) -> Array[lookupHash]
  def cache_key: (String secret_id, String version_stage) -> String

  type lookupHash = { id: String, version_stage: String }
  type cacheResult = { cached: Array[Hash[Symbol, untyped]], missing: Array[lookupHash] }
end
